#define CONVERTER_DOT                             1
#define CONVERTER_HIDE                            2
#define CONVERTER_SHOW                            3
#define CONVERTER_SLASH                           4
#define CONVERTER_EXTERNAL                        5
#define CONVERTER_IDENTIFIER                      6
#define CONVERTER_MINUS                           7
#define CONVERTER_IF                              8
#define CONVERTER_COMMA                           9
#define CONVERTER_NOT                            10
#define CONVERTER_STRING                         11
#define CONVERTER_NUMBER                         12
#define CONVERTER_SUP                            13
#define CONVERTER_INF                            14
#define CONVERTER_LBRAC                          15
#define CONVERTER_RBRAC                          16
#define CONVERTER_ASSIGN                         17
#define CONVERTER_SUM                            18
#define CONVERTER_LSBRAC                         19
#define CONVERTER_RSBRAC                         20
#define CONVERTER_COUNT                          21
#define CONVERTER_LCBRAC                         22
#define CONVERTER_RCBRAC                         23
#define CONVERTER_AVG                            24
#define CONVERTER_MIN                            25
#define CONVERTER_MAX                            26
#define CONVERTER_EVEN                           27
#define CONVERTER_ODD                            28
#define CONVERTER_VBAR                           29
#define CONVERTER_MINIMIZE                       30
#define CONVERTER_MAXIMIZE                       31
#define CONVERTER_COMPUTE                        32
#define CONVERTER_AT                             33
