#define PARSER_Rule                            1
#define PARSER_SEM                             2
#define PARSER_DOTS                            3
#define PARSER_XOR                             4
#define PARSER_QUESTION                        5
#define PARSER_AND                             6
#define PARSER_PLUS                            7
#define PARSER_MINUS                           8
#define PARSER_MULT                            9
#define PARSER_SLASH                          10
#define PARSER_MOD                            11
#define PARSER_PMOD                           12
#define PARSER_DIV                            13
#define PARSER_PDIV                           14
#define PARSER_POW                            15
#define PARSER_PPOW                           16
#define PARSER_UMINUS                         17
#define PARSER_UBNOT                          18
#define PARSER_DSEM                           19
#define PARSER_COMMA                          20
#define PARSER_VBAR                           21
#define PARSER_DOT                            22
#define PARSER_INCLUDE                        23
#define PARSER_STRING                         24
#define PARSER_HIDE                           25
#define PARSER_SHOW                           26
#define PARSER_NUMBER                         27
#define PARSER_CONST                          28
#define PARSER_IDENTIFIER                     29
#define PARSER_ASSIGN                         30
#define PARSER_DOMAIN                         31
#define PARSER_LBRAC                          32
#define PARSER_RBRAC                          33
#define PARSER_EXTERNAL                       34
#define PARSER_CUMULATIVE                     35
#define PARSER_VOLATILE                       36
#define PARSER_BASE                           37
#define PARSER_COLON                          38
#define PARSER_VARIABLE                       39
#define PARSER_IF                             40
#define PARSER_NOT                            41
#define PARSER_CASSIGN                        42
#define PARSER_GREATER                        43
#define PARSER_LOWER                          44
#define PARSER_GTHAN                          45
#define PARSER_LTHAN                          46
#define PARSER_EQUAL                          47
#define PARSER_INEQUAL                        48
#define PARSER_ANONYMOUS                      49
#define PARSER_INFIMUM                        50
#define PARSER_SUPREMUM                       51
#define PARSER_PABS                           52
#define PARSER_AT                             53
#define PARSER_BNOT                           54
#define PARSER_SUM                            55
#define PARSER_LSBRAC                         56
#define PARSER_RSBRAC                         57
#define PARSER_AVG                            58
#define PARSER_COUNT                          59
#define PARSER_LCBRAC                         60
#define PARSER_RCBRAC                         61
#define PARSER_EVEN                           62
#define PARSER_ODD                            63
#define PARSER_MIN                            64
#define PARSER_MAX                            65
#define PARSER_MINIMIZE                       66
#define PARSER_MAXIMIZE                       67
#define PARSER_COMPUTE                        68
#define PARSER_INCR                           69
