/* Generated by re2c 0.13.5 on Thu Jan 26 12:49:49 2012 */
#line 1 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
// Copyright (c) 2009, Roland Kaminski <kaminski@cs.uni-potsdam.de>
//
// This file is part of gringo.
//
// gringo is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// gringo is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with gringo.  If not, see <http://www.gnu.org/licenses/>.

#include <gringo/parser.h>
#include <gringo/varterm.h>
#include <gringo/inclit.h>
#include <gringo/varterm.h>
#include <gringo/constterm.h>
#include <gringo/prgvisitor.h>
#include <gringo/predlit.h>
#include <gringo/rule.h>
#include <gringo/streams.h>
#include <gringo/grounder.h>
#include <gringo/statement.h>
#include <gringo/exceptions.h>
#include "parser_impl.h"

void *parserAlloc(void *(*mallocProc)(size_t));
void parserFree(void *p, void (*freeProc)(void*));
void parser(void *yyp, int yymajor, Parser::Token yyminor, Parser *pParser);

Parser::DomStm::DomStm(const Loc &l, uint32_t idx, uint32_t id, const VarSigVec &vars)
	: loc(l)
	, idx(idx)
	, id(id)
	, vars(vars)
{
}

Parser::Parser(Grounder *g, IncConfig &config, Streams &streams, bool compat)
	: g_(g)
	, config_(config)
	, streams_(streams)
	, parser_(parserAlloc(malloc))
	, error_(false)
	, include_(std::numeric_limits<uint32_t>::max())
	, iPart_(IPART_BASE)
	, iId_(0)
	, iVar_(0)
	, iAdded_(0)
	, compat_(compat)
{
}

#line 68 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"


int Parser::lex()
{
start:
	char *luaEnd = 0;
	int bc = 0;
	start();
	token_.line   = line();
	token_.column = column();
	
#line 74 "src/parser.cpp"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if ((YYLIMIT - YYCURSOR) < 11) YYFILL(11);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy3;
	case '\n':	goto yy4;
	case '!':	goto yy55;
	case '"':	goto yy18;
	case '#':	goto yy6;
	case '%':	goto yy68;
	case '&':	goto yy60;
	case '(':	goto yy33;
	case ')':	goto yy35;
	case '*':	goto yy45;
	case '+':	goto yy41;
	case ',':	goto yy25;
	case '-':	goto yy43;
	case '.':	goto yy21;
	case '/':	goto yy56;
	case '0':	goto yy13;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy15;
	case ':':	goto yy23;
	case ';':	goto yy19;
	case '<':	goto yy51;
	case '=':	goto yy53;
	case '>':	goto yy49;
	case '?':	goto yy66;
	case '@':	goto yy58;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	goto yy16;
	case '[':	goto yy29;
	case '\\':	goto yy47;
	case ']':	goto yy31;
	case '^':	goto yy62;
	case '_':	goto yy10;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy12;
	case 'n':	goto yy8;
	case '{':	goto yy37;
	case '|':	goto yy27;
	case '}':	goto yy39;
	case '~':	goto yy64;
	default:	goto yy70;
	}
yy2:
#line 79 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ goto start; }
#line 182 "src/parser.cpp"
yy3:
	yych = *++YYCURSOR;
	goto yy252;
yy4:
	++YYCURSOR;
#line 80 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ if(eof()) return 0; step(); goto start; }
#line 190 "src/parser.cpp"
yy6:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy108;
	case 'b':	goto yy118;
	case 'c':	goto yy114;
	case 'd':	goto yy110;
	case 'e':	goto yy113;
	case 'h':	goto yy119;
	case 'i':	goto yy116;
	case 'm':	goto yy111;
	case 'o':	goto yy112;
	case 'p':	goto yy109;
	case 's':	goto yy115;
	case 'v':	goto yy117;
	default:	goto yy7;
	}
yy7:
#line 148 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ syntaxError(); goto start; }
#line 212 "src/parser.cpp"
yy8:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'o':	goto yy105;
	default:	goto yy102;
	}
yy9:
#line 97 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ token_.index  = g_->index(string()); return PARSER_IDENTIFIER; }
#line 222 "src/parser.cpp"
yy10:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	goto yy97;
	case '_':	goto yy103;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy101;
	default:	goto yy11;
	}
yy11:
#line 100 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_ANONYMOUS; }
#line 285 "src/parser.cpp"
yy12:
	yych = *++YYCURSOR;
	goto yy102;
yy13:
	++YYCURSOR;
yy14:
#line 98 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ token_.number = integer(); return PARSER_NUMBER; }
#line 294 "src/parser.cpp"
yy15:
	yych = *++YYCURSOR;
	goto yy100;
yy16:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy98;
yy17:
#line 99 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ token_.index = g_->index(string()); return PARSER_VARIABLE; }
#line 305 "src/parser.cpp"
yy18:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy7;
	default:	goto yy92;
	}
yy19:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case ';':	goto yy89;
	default:	goto yy20;
	}
yy20:
#line 114 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_SEM; }
#line 322 "src/parser.cpp"
yy21:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':	goto yy87;
	default:	goto yy22;
	}
yy22:
#line 116 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_DOT; }
#line 332 "src/parser.cpp"
yy23:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '-':	goto yy85;
	case '=':	goto yy83;
	default:	goto yy24;
	}
yy24:
#line 117 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_COLON; }
#line 343 "src/parser.cpp"
yy25:
	++YYCURSOR;
#line 119 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_COMMA; }
#line 348 "src/parser.cpp"
yy27:
	++YYCURSOR;
#line 120 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_VBAR; }
#line 353 "src/parser.cpp"
yy29:
	++YYCURSOR;
#line 121 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_LSBRAC; }
#line 358 "src/parser.cpp"
yy31:
	++YYCURSOR;
#line 122 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_RSBRAC; }
#line 363 "src/parser.cpp"
yy33:
	++YYCURSOR;
#line 123 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_LBRAC; }
#line 368 "src/parser.cpp"
yy35:
	++YYCURSOR;
#line 124 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_RBRAC; }
#line 373 "src/parser.cpp"
yy37:
	++YYCURSOR;
#line 125 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_LCBRAC; }
#line 378 "src/parser.cpp"
yy39:
	++YYCURSOR;
#line 126 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_RCBRAC; }
#line 383 "src/parser.cpp"
yy41:
	++YYCURSOR;
#line 127 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_PLUS; }
#line 388 "src/parser.cpp"
yy43:
	++YYCURSOR;
#line 128 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MINUS; }
#line 393 "src/parser.cpp"
yy45:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy81;
	default:	goto yy46;
	}
yy46:
#line 131 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MULT; }
#line 403 "src/parser.cpp"
yy47:
	++YYCURSOR;
#line 130 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MOD; }
#line 408 "src/parser.cpp"
yy49:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy79;
	default:	goto yy50;
	}
yy50:
#line 132 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_GREATER; }
#line 418 "src/parser.cpp"
yy51:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy77;
	default:	goto yy52;
	}
yy52:
#line 133 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_LOWER; }
#line 428 "src/parser.cpp"
yy53:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy75;
	default:	goto yy54;
	}
yy54:
#line 139 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_ASSIGN; }
#line 438 "src/parser.cpp"
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy73;
	default:	goto yy7;
	}
yy56:
	++YYCURSOR;
#line 140 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_SLASH; }
#line 449 "src/parser.cpp"
yy58:
	++YYCURSOR;
#line 141 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_AT; }
#line 454 "src/parser.cpp"
yy60:
	++YYCURSOR;
#line 142 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_AND; }
#line 459 "src/parser.cpp"
yy62:
	++YYCURSOR;
#line 143 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_XOR; }
#line 464 "src/parser.cpp"
yy64:
	++YYCURSOR;
#line 144 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_BNOT; }
#line 469 "src/parser.cpp"
yy66:
	++YYCURSOR;
#line 145 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_QUESTION; }
#line 474 "src/parser.cpp"
yy68:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy71;
	default:	goto yy69;
	}
yy69:
#line 147 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ goto comment; }
#line 484 "src/parser.cpp"
yy70:
	yych = *++YYCURSOR;
	goto yy7;
yy71:
	++YYCURSOR;
#line 146 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ bc++; goto blockcomment; }
#line 492 "src/parser.cpp"
yy73:
	++YYCURSOR;
#line 137 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_INEQUAL; }
#line 497 "src/parser.cpp"
yy75:
	++YYCURSOR;
#line 136 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_EQUAL; }
#line 502 "src/parser.cpp"
yy77:
	++YYCURSOR;
#line 135 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_LTHAN; }
#line 507 "src/parser.cpp"
yy79:
	++YYCURSOR;
#line 134 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_GTHAN; }
#line 512 "src/parser.cpp"
yy81:
	++YYCURSOR;
#line 129 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_POW; }
#line 517 "src/parser.cpp"
yy83:
	++YYCURSOR;
#line 138 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_CASSIGN; }
#line 522 "src/parser.cpp"
yy85:
	++YYCURSOR;
#line 118 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_IF; }
#line 527 "src/parser.cpp"
yy87:
	++YYCURSOR;
#line 115 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_DOTS; }
#line 532 "src/parser.cpp"
yy89:
	++YYCURSOR;
#line 113 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_DSEM; }
#line 537 "src/parser.cpp"
yy91:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy92:
	switch (yych) {
	case '\n':	goto yy93;
	case '"':	goto yy95;
	case '\\':	goto yy94;
	default:	goto yy91;
	}
yy93:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy7;
	case 1: 	goto yy11;
	case 2: 	goto yy218;
	case 3: 	goto yy226;
	}
yy94:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':
	case '\\':
	case 'n':	goto yy91;
	default:	goto yy93;
	}
yy95:
	++YYCURSOR;
#line 101 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ token_.index = g_->index(g_->unquote(string(1,1))); return PARSER_STRING; }
#line 571 "src/parser.cpp"
yy97:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy98:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy17;
	}
yy99:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy100:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy99;
	default:	goto yy14;
	}
yy101:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy102:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy101;
	default:	goto yy9;
	}
yy103:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	goto yy97;
	case '_':	goto yy103;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy101;
	default:	goto yy93;
	}
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy106;
	default:	goto yy102;
	}
yy106:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy101;
	default:	goto yy107;
	}
yy107:
#line 82 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_NOT; }
#line 869 "src/parser.cpp"
yy108:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy246;
	case 'v':	goto yy245;
	default:	goto yy93;
	}
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy242;
	default:	goto yy93;
	}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy234;
	case 'o':	goto yy233;
	default:	goto yy93;
	}
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy213;
	case 'i':	goto yy212;
	case 'o':	goto yy214;
	default:	goto yy93;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy209;
	default:	goto yy93;
	}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'v':	goto yy198;
	case 'x':	goto yy197;
	default:	goto yy93;
	}
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy172;
	case 'u':	goto yy173;
	default:	goto yy93;
	}
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy158;
	case 'u':	goto yy159;
	default:	goto yy93;
	}
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy145;
	default:	goto yy93;
	}
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy137;
	default:	goto yy93;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy125;
	case 'e':	goto yy124;
	default:	goto yy93;
	}
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy120;
	default:	goto yy93;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy121;
	default:	goto yy93;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy122;
	default:	goto yy93;
	}
yy122:
	++YYCURSOR;
#line 85 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_HIDE; }
#line 966 "src/parser.cpp"
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy129;
	default:	goto yy93;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy126;
	default:	goto yy93;
	}
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy127;
	default:	goto yy93;
	}
yy127:
	++YYCURSOR;
#line 90 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_BASE; }
#line 989 "src/parser.cpp"
yy129:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy130;
	default:	goto yy93;
	}
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy131;
	default:	goto yy93;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy132;
	default:	goto yy93;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy133;
	default:	goto yy93;
	}
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy134;
	default:	goto yy93;
	}
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy135;
	default:	goto yy93;
	}
yy135:
	++YYCURSOR;
#line 81 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ luaBegin_ = token_.loc(); goto lua; }
#line 1030 "src/parser.cpp"
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy138;
	default:	goto yy93;
	}
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy139;
	default:	goto yy93;
	}
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy140;
	default:	goto yy93;
	}
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy141;
	default:	goto yy93;
	}
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy142;
	default:	goto yy93;
	}
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy143;
	default:	goto yy93;
	}
yy143:
	++YYCURSOR;
#line 92 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_VOLATILE; }
#line 1071 "src/parser.cpp"
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy147;
	case 'f':	goto yy146;
	default:	goto yy93;
	}
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy153;
	default:	goto yy93;
	}
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy148;
	default:	goto yy93;
	}
yy148:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy149;
	default:	goto yy93;
	}
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy150;
	default:	goto yy93;
	}
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy151;
	default:	goto yy93;
	}
yy151:
	++YYCURSOR;
#line 83 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_INCLUDE; }
#line 1113 "src/parser.cpp"
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy154;
	default:	goto yy93;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy155;
	default:	goto yy93;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy156;
	default:	goto yy93;
	}
yy156:
	++YYCURSOR;
#line 95 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_INFIMUM; }
#line 1136 "src/parser.cpp"
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy169;
	default:	goto yy93;
	}
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy160;
	case 'p':	goto yy162;
	default:	goto yy93;
	}
yy160:
	++YYCURSOR;
#line 102 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_SUM; }
#line 1154 "src/parser.cpp"
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy163;
	default:	goto yy93;
	}
yy163:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy164;
	default:	goto yy93;
	}
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy165;
	default:	goto yy93;
	}
yy165:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy166;
	default:	goto yy93;
	}
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy167;
	default:	goto yy93;
	}
yy167:
	++YYCURSOR;
#line 96 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_SUPREMUM; }
#line 1189 "src/parser.cpp"
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy170;
	default:	goto yy93;
	}
yy170:
	++YYCURSOR;
#line 84 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_SHOW; }
#line 1200 "src/parser.cpp"
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy184;
	case 'n':	goto yy185;
	case 'u':	goto yy183;
	default:	goto yy93;
	}
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy174;
	default:	goto yy93;
	}
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy175;
	default:	goto yy93;
	}
yy175:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy176;
	default:	goto yy93;
	}
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy177;
	default:	goto yy93;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy178;
	default:	goto yy93;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy179;
	default:	goto yy93;
	}
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'v':	goto yy180;
	default:	goto yy93;
	}
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy181;
	default:	goto yy93;
	}
yy181:
	++YYCURSOR;
#line 91 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_CUMULATIVE; }
#line 1261 "src/parser.cpp"
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy194;
	default:	goto yy93;
	}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy189;
	default:	goto yy93;
	}
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy186;
	default:	goto yy93;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy187;
	default:	goto yy93;
	}
yy187:
	++YYCURSOR;
#line 86 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_CONST; }
#line 1290 "src/parser.cpp"
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy190;
	default:	goto yy93;
	}
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy191;
	default:	goto yy93;
	}
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy192;
	default:	goto yy93;
	}
yy192:
	++YYCURSOR;
#line 89 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_COMPUTE; }
#line 1313 "src/parser.cpp"
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy195;
	default:	goto yy93;
	}
yy195:
	++YYCURSOR;
#line 103 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_COUNT; }
#line 1324 "src/parser.cpp"
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy202;
	default:	goto yy93;
	}
yy198:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy199;
	default:	goto yy93;
	}
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy200;
	default:	goto yy93;
	}
yy200:
	++YYCURSOR;
#line 106 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_EVEN; }
#line 1347 "src/parser.cpp"
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy203;
	default:	goto yy93;
	}
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy204;
	default:	goto yy93;
	}
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy205;
	default:	goto yy93;
	}
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy206;
	default:	goto yy93;
	}
yy206:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy207;
	default:	goto yy93;
	}
yy207:
	++YYCURSOR;
#line 94 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_EXTERNAL; }
#line 1382 "src/parser.cpp"
yy209:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy210;
	default:	goto yy93;
	}
yy210:
	++YYCURSOR;
#line 107 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_ODD; }
#line 1393 "src/parser.cpp"
yy212:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy225;
	default:	goto yy93;
	}
yy213:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy217;
	default:	goto yy93;
	}
yy214:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy215;
	default:	goto yy93;
	}
yy215:
	++YYCURSOR;
#line 109 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_PMOD; }
#line 1416 "src/parser.cpp"
yy217:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'i':	goto yy219;
	default:	goto yy218;
	}
yy218:
#line 105 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MAX; }
#line 1427 "src/parser.cpp"
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy220;
	default:	goto yy93;
	}
yy220:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy221;
	default:	goto yy93;
	}
yy221:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':
	case 'z':	goto yy222;
	default:	goto yy93;
	}
yy222:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy223;
	default:	goto yy93;
	}
yy223:
	++YYCURSOR;
#line 88 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MAXIMIZE; }
#line 1457 "src/parser.cpp"
yy225:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'i':	goto yy227;
	default:	goto yy226;
	}
yy226:
#line 104 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MIN; }
#line 1468 "src/parser.cpp"
yy227:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy228;
	default:	goto yy93;
	}
yy228:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy229;
	default:	goto yy93;
	}
yy229:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':
	case 'z':	goto yy230;
	default:	goto yy93;
	}
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy231;
	default:	goto yy93;
	}
yy231:
	++YYCURSOR;
#line 87 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MINIMIZE; }
#line 1498 "src/parser.cpp"
yy233:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy237;
	default:	goto yy93;
	}
yy234:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'v':	goto yy235;
	default:	goto yy93;
	}
yy235:
	++YYCURSOR;
#line 110 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_PDIV; }
#line 1515 "src/parser.cpp"
yy237:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy238;
	default:	goto yy93;
	}
yy238:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy239;
	default:	goto yy93;
	}
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy240;
	default:	goto yy93;
	}
yy240:
	++YYCURSOR;
#line 93 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_DOMAIN; }
#line 1538 "src/parser.cpp"
yy242:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy243;
	default:	goto yy93;
	}
yy243:
	++YYCURSOR;
#line 111 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_PPOW; }
#line 1549 "src/parser.cpp"
yy245:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy249;
	default:	goto yy93;
	}
yy246:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy247;
	default:	goto yy93;
	}
yy247:
	++YYCURSOR;
#line 112 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_PABS; }
#line 1566 "src/parser.cpp"
yy249:
	++YYCURSOR;
#line 108 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_AVG; }
#line 1571 "src/parser.cpp"
yy251:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy252:
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy251;
	default:	goto yy2;
	}
}
#line 149 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"

lua:
	luaEnd = state().cursor_;
	
#line 1589 "src/parser.cpp"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 8) YYFILL(8);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy257;
	case '#':	goto yy255;
	default:	goto yy259;
	}
yy255:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'e':	goto yy260;
	default:	goto yy256;
	}
yy256:
#line 155 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ goto lua; }
#line 1608 "src/parser.cpp"
yy257:
	++YYCURSOR;
#line 154 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ if(eof()) { syntaxError(); return 0; } step(); goto lua; }
#line 1613 "src/parser.cpp"
yy259:
	yych = *++YYCURSOR;
	goto yy256;
yy260:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy262;
	default:	goto yy261;
	}
yy261:
	YYCURSOR = YYMARKER;
	goto yy256;
yy262:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy263;
	default:	goto yy261;
	}
yy263:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy264;
	default:	goto yy261;
	}
yy264:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy265;
	default:	goto yy261;
	}
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy266;
	default:	goto yy261;
	}
yy266:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy267;
	default:	goto yy261;
	}
yy267:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy267;
	case '.':	goto yy269;
	default:	goto yy261;
	}
yy269:
	++YYCURSOR;
#line 153 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ grounder()->luaExec(luaBegin_, string(10, state().cursor_ - luaEnd)); goto start; }
#line 1671 "src/parser.cpp"
}
#line 156 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"

blockcomment:
	
#line 1677 "src/parser.cpp"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy277;
	case '%':	goto yy275;
	case '*':	goto yy273;
	default:	goto yy279;
	}
yy273:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '%':	goto yy282;
	default:	goto yy274;
	}
yy274:
#line 163 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ goto blockcomment; }
#line 1697 "src/parser.cpp"
yy275:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy280;
	default:	goto yy276;
	}
yy276:
#line 161 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ goto comment; }
#line 1707 "src/parser.cpp"
yy277:
	++YYCURSOR;
#line 162 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ if(eof()) { syntaxError(); return 0; } step(); goto blockcomment; }
#line 1712 "src/parser.cpp"
yy279:
	yych = *++YYCURSOR;
	goto yy274;
yy280:
	++YYCURSOR;
#line 160 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ bc++; goto blockcomment; }
#line 1720 "src/parser.cpp"
yy282:
	++YYCURSOR;
#line 159 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ if(--bc == 0) goto start; goto blockcomment; }
#line 1725 "src/parser.cpp"
}
#line 164 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"

comment:
	
#line 1731 "src/parser.cpp"
{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy286;
	default:	goto yy288;
	}
yy286:
	++YYCURSOR;
#line 167 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ if(eof()) { if(bc > 0) syntaxError(); return 0; } step(); if(bc > 0) goto blockcomment; goto start; }
#line 1744 "src/parser.cpp"
yy288:
	++YYCURSOR;
#line 168 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ goto comment; }
#line 1749 "src/parser.cpp"
}
#line 169 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"

}

int Parser::lex_compat()
{
start:
	char *luaEnd = 0;
	int bc = 0;
	start();
	token_.line   = line();
	token_.column = column();
	
#line 1764 "src/parser.cpp"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 11) YYFILL(11);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy301;
	case '\n':	goto yy302;
	case '!':	goto yy352;
	case '"':	goto yy315;
	case '#':	goto yy304;
	case '%':	goto yy365;
	case '&':	goto yy357;
	case '(':	goto yy330;
	case ')':	goto yy332;
	case '*':	goto yy342;
	case '+':	goto yy338;
	case ',':	goto yy322;
	case '-':	goto yy340;
	case '.':	goto yy318;
	case '/':	goto yy353;
	case '0':	goto yy310;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy312;
	case ':':	goto yy320;
	case ';':	goto yy316;
	case '<':	goto yy348;
	case '=':	goto yy350;
	case '>':	goto yy346;
	case '?':	goto yy363;
	case '@':	goto yy355;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	goto yy313;
	case '[':	goto yy326;
	case '\\':	goto yy344;
	case ']':	goto yy328;
	case '^':	goto yy359;
	case '_':	goto yy307;
	case 'a':	goto yy300;
	case 'b':
	case 'e':
	case 'f':
	case 'g':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'o':
	case 'q':
	case 'r':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy309;
	case 'c':	goto yy296;
	case 'd':	goto yy298;
	case 'h':	goto yy295;
	case 'm':	goto yy297;
	case 'n':	goto yy306;
	case 'p':	goto yy299;
	case 's':	goto yy293;
	case '{':	goto yy334;
	case '|':	goto yy324;
	case '}':	goto yy336;
	case '~':	goto yy361;
	default:	goto yy367;
	}
yy292:
#line 193 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ goto start; }
#line 1871 "src/parser.cpp"
yy293:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'h':	goto yy593;
	default:	goto yy399;
	}
yy294:
#line 211 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ token_.index  = g_->index(string()); return PARSER_IDENTIFIER; }
#line 1881 "src/parser.cpp"
yy295:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy589;
	default:	goto yy399;
	}
yy296:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy578;
	default:	goto yy399;
	}
yy297:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy559;
	case 'i':	goto yy560;
	case 'o':	goto yy561;
	default:	goto yy399;
	}
yy298:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy556;
	default:	goto yy399;
	}
yy299:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy553;
	default:	goto yy399;
	}
yy300:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy550;
	default:	goto yy399;
	}
yy301:
	yych = *++YYCURSOR;
	goto yy549;
yy302:
	++YYCURSOR;
#line 194 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ if(eof()) return 0; step(); goto start; }
#line 1927 "src/parser.cpp"
yy304:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy405;
	case 'b':	goto yy415;
	case 'c':	goto yy411;
	case 'd':	goto yy407;
	case 'e':	goto yy410;
	case 'h':	goto yy416;
	case 'i':	goto yy413;
	case 'm':	goto yy408;
	case 'o':	goto yy409;
	case 'p':	goto yy406;
	case 's':	goto yy412;
	case 'v':	goto yy414;
	default:	goto yy305;
	}
yy305:
#line 262 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ syntaxError(); goto start; }
#line 1949 "src/parser.cpp"
yy306:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy402;
	default:	goto yy399;
	}
yy307:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	goto yy394;
	case '_':	goto yy400;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy398;
	default:	goto yy308;
	}
yy308:
#line 214 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_ANONYMOUS; }
#line 2018 "src/parser.cpp"
yy309:
	yych = *++YYCURSOR;
	goto yy399;
yy310:
	++YYCURSOR;
yy311:
#line 212 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ token_.number = integer(); return PARSER_NUMBER; }
#line 2027 "src/parser.cpp"
yy312:
	yych = *++YYCURSOR;
	goto yy397;
yy313:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy395;
yy314:
#line 213 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ token_.index = g_->index(string()); return PARSER_VARIABLE; }
#line 2038 "src/parser.cpp"
yy315:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy305;
	default:	goto yy389;
	}
yy316:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case ';':	goto yy386;
	default:	goto yy317;
	}
yy317:
#line 228 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_SEM; }
#line 2055 "src/parser.cpp"
yy318:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':	goto yy384;
	default:	goto yy319;
	}
yy319:
#line 230 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_DOT; }
#line 2065 "src/parser.cpp"
yy320:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '-':	goto yy382;
	case '=':	goto yy380;
	default:	goto yy321;
	}
yy321:
#line 231 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_COLON; }
#line 2076 "src/parser.cpp"
yy322:
	++YYCURSOR;
#line 233 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_COMMA; }
#line 2081 "src/parser.cpp"
yy324:
	++YYCURSOR;
#line 234 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_VBAR; }
#line 2086 "src/parser.cpp"
yy326:
	++YYCURSOR;
#line 235 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_LSBRAC; }
#line 2091 "src/parser.cpp"
yy328:
	++YYCURSOR;
#line 236 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_RSBRAC; }
#line 2096 "src/parser.cpp"
yy330:
	++YYCURSOR;
#line 237 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_LBRAC; }
#line 2101 "src/parser.cpp"
yy332:
	++YYCURSOR;
#line 238 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_RBRAC; }
#line 2106 "src/parser.cpp"
yy334:
	++YYCURSOR;
#line 239 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_LCBRAC; }
#line 2111 "src/parser.cpp"
yy336:
	++YYCURSOR;
#line 240 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_RCBRAC; }
#line 2116 "src/parser.cpp"
yy338:
	++YYCURSOR;
#line 241 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_PLUS; }
#line 2121 "src/parser.cpp"
yy340:
	++YYCURSOR;
#line 242 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MINUS; }
#line 2126 "src/parser.cpp"
yy342:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy378;
	default:	goto yy343;
	}
yy343:
#line 245 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MULT; }
#line 2136 "src/parser.cpp"
yy344:
	++YYCURSOR;
#line 244 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MOD; }
#line 2141 "src/parser.cpp"
yy346:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy376;
	default:	goto yy347;
	}
yy347:
#line 246 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_GREATER; }
#line 2151 "src/parser.cpp"
yy348:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy374;
	default:	goto yy349;
	}
yy349:
#line 247 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_LOWER; }
#line 2161 "src/parser.cpp"
yy350:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy372;
	default:	goto yy351;
	}
yy351:
#line 253 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_ASSIGN; }
#line 2171 "src/parser.cpp"
yy352:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy370;
	default:	goto yy305;
	}
yy353:
	++YYCURSOR;
#line 254 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_SLASH; }
#line 2182 "src/parser.cpp"
yy355:
	++YYCURSOR;
#line 255 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_AT; }
#line 2187 "src/parser.cpp"
yy357:
	++YYCURSOR;
#line 256 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_AND; }
#line 2192 "src/parser.cpp"
yy359:
	++YYCURSOR;
#line 257 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_XOR; }
#line 2197 "src/parser.cpp"
yy361:
	++YYCURSOR;
#line 258 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_BNOT; }
#line 2202 "src/parser.cpp"
yy363:
	++YYCURSOR;
#line 259 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_QUESTION; }
#line 2207 "src/parser.cpp"
yy365:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy368;
	default:	goto yy366;
	}
yy366:
#line 261 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ goto comment; }
#line 2217 "src/parser.cpp"
yy367:
	yych = *++YYCURSOR;
	goto yy305;
yy368:
	++YYCURSOR;
#line 260 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ bc++; goto blockcomment; }
#line 2225 "src/parser.cpp"
yy370:
	++YYCURSOR;
#line 251 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_INEQUAL; }
#line 2230 "src/parser.cpp"
yy372:
	++YYCURSOR;
#line 250 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_EQUAL; }
#line 2235 "src/parser.cpp"
yy374:
	++YYCURSOR;
#line 249 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_LTHAN; }
#line 2240 "src/parser.cpp"
yy376:
	++YYCURSOR;
#line 248 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_GTHAN; }
#line 2245 "src/parser.cpp"
yy378:
	++YYCURSOR;
#line 243 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_POW; }
#line 2250 "src/parser.cpp"
yy380:
	++YYCURSOR;
#line 252 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_CASSIGN; }
#line 2255 "src/parser.cpp"
yy382:
	++YYCURSOR;
#line 232 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_IF; }
#line 2260 "src/parser.cpp"
yy384:
	++YYCURSOR;
#line 229 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_DOTS; }
#line 2265 "src/parser.cpp"
yy386:
	++YYCURSOR;
#line 227 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_DSEM; }
#line 2270 "src/parser.cpp"
yy388:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy389:
	switch (yych) {
	case '\n':	goto yy390;
	case '"':	goto yy392;
	case '\\':	goto yy391;
	default:	goto yy388;
	}
yy390:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy305;
	case 1: 	goto yy308;
	case 2: 	goto yy515;
	case 3: 	goto yy523;
	}
yy391:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':
	case '\\':
	case 'n':	goto yy388;
	default:	goto yy390;
	}
yy392:
	++YYCURSOR;
#line 215 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ token_.index = g_->index(g_->unquote(string(1,1))); return PARSER_STRING; }
#line 2304 "src/parser.cpp"
yy394:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy395:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy394;
	default:	goto yy314;
	}
yy396:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy397:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy396;
	default:	goto yy311;
	}
yy398:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy399:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy398;
	default:	goto yy294;
	}
yy400:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	goto yy394;
	case '_':	goto yy400;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy398;
	default:	goto yy390;
	}
yy402:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy403;
	default:	goto yy399;
	}
yy403:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy398;
	default:	goto yy404;
	}
yy404:
#line 196 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_NOT; }
#line 2602 "src/parser.cpp"
yy405:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy543;
	case 'v':	goto yy542;
	default:	goto yy390;
	}
yy406:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy539;
	default:	goto yy390;
	}
yy407:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy531;
	case 'o':	goto yy530;
	default:	goto yy390;
	}
yy408:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy510;
	case 'i':	goto yy509;
	case 'o':	goto yy511;
	default:	goto yy390;
	}
yy409:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy506;
	default:	goto yy390;
	}
yy410:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'v':	goto yy495;
	case 'x':	goto yy494;
	default:	goto yy390;
	}
yy411:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy469;
	case 'u':	goto yy470;
	default:	goto yy390;
	}
yy412:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy455;
	case 'u':	goto yy456;
	default:	goto yy390;
	}
yy413:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy442;
	default:	goto yy390;
	}
yy414:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy434;
	default:	goto yy390;
	}
yy415:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy422;
	case 'e':	goto yy421;
	default:	goto yy390;
	}
yy416:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy417;
	default:	goto yy390;
	}
yy417:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy418;
	default:	goto yy390;
	}
yy418:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy419;
	default:	goto yy390;
	}
yy419:
	++YYCURSOR;
#line 199 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_HIDE; }
#line 2699 "src/parser.cpp"
yy421:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy426;
	default:	goto yy390;
	}
yy422:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy423;
	default:	goto yy390;
	}
yy423:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy424;
	default:	goto yy390;
	}
yy424:
	++YYCURSOR;
#line 204 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_BASE; }
#line 2722 "src/parser.cpp"
yy426:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy427;
	default:	goto yy390;
	}
yy427:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy428;
	default:	goto yy390;
	}
yy428:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy429;
	default:	goto yy390;
	}
yy429:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy430;
	default:	goto yy390;
	}
yy430:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy431;
	default:	goto yy390;
	}
yy431:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy432;
	default:	goto yy390;
	}
yy432:
	++YYCURSOR;
#line 195 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ luaBegin_ = token_.loc(); goto lua; }
#line 2763 "src/parser.cpp"
yy434:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy435;
	default:	goto yy390;
	}
yy435:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy436;
	default:	goto yy390;
	}
yy436:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy437;
	default:	goto yy390;
	}
yy437:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy438;
	default:	goto yy390;
	}
yy438:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy439;
	default:	goto yy390;
	}
yy439:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy440;
	default:	goto yy390;
	}
yy440:
	++YYCURSOR;
#line 206 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_VOLATILE; }
#line 2804 "src/parser.cpp"
yy442:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy444;
	case 'f':	goto yy443;
	default:	goto yy390;
	}
yy443:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy450;
	default:	goto yy390;
	}
yy444:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy445;
	default:	goto yy390;
	}
yy445:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy446;
	default:	goto yy390;
	}
yy446:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy447;
	default:	goto yy390;
	}
yy447:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy448;
	default:	goto yy390;
	}
yy448:
	++YYCURSOR;
#line 197 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_INCLUDE; }
#line 2846 "src/parser.cpp"
yy450:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy451;
	default:	goto yy390;
	}
yy451:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy452;
	default:	goto yy390;
	}
yy452:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy453;
	default:	goto yy390;
	}
yy453:
	++YYCURSOR;
#line 209 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_INFIMUM; }
#line 2869 "src/parser.cpp"
yy455:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy466;
	default:	goto yy390;
	}
yy456:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy457;
	case 'p':	goto yy459;
	default:	goto yy390;
	}
yy457:
	++YYCURSOR;
#line 216 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_SUM; }
#line 2887 "src/parser.cpp"
yy459:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy460;
	default:	goto yy390;
	}
yy460:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy461;
	default:	goto yy390;
	}
yy461:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy462;
	default:	goto yy390;
	}
yy462:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy463;
	default:	goto yy390;
	}
yy463:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy464;
	default:	goto yy390;
	}
yy464:
	++YYCURSOR;
#line 210 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_SUPREMUM; }
#line 2922 "src/parser.cpp"
yy466:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy467;
	default:	goto yy390;
	}
yy467:
	++YYCURSOR;
#line 198 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_SHOW; }
#line 2933 "src/parser.cpp"
yy469:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy481;
	case 'n':	goto yy482;
	case 'u':	goto yy480;
	default:	goto yy390;
	}
yy470:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy471;
	default:	goto yy390;
	}
yy471:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy472;
	default:	goto yy390;
	}
yy472:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy473;
	default:	goto yy390;
	}
yy473:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy474;
	default:	goto yy390;
	}
yy474:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy475;
	default:	goto yy390;
	}
yy475:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy476;
	default:	goto yy390;
	}
yy476:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'v':	goto yy477;
	default:	goto yy390;
	}
yy477:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy478;
	default:	goto yy390;
	}
yy478:
	++YYCURSOR;
#line 205 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_CUMULATIVE; }
#line 2994 "src/parser.cpp"
yy480:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy491;
	default:	goto yy390;
	}
yy481:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy486;
	default:	goto yy390;
	}
yy482:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy483;
	default:	goto yy390;
	}
yy483:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy484;
	default:	goto yy390;
	}
yy484:
	++YYCURSOR;
#line 200 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_CONST; }
#line 3023 "src/parser.cpp"
yy486:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy487;
	default:	goto yy390;
	}
yy487:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy488;
	default:	goto yy390;
	}
yy488:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy489;
	default:	goto yy390;
	}
yy489:
	++YYCURSOR;
#line 203 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_COMPUTE; }
#line 3046 "src/parser.cpp"
yy491:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy492;
	default:	goto yy390;
	}
yy492:
	++YYCURSOR;
#line 217 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_COUNT; }
#line 3057 "src/parser.cpp"
yy494:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy499;
	default:	goto yy390;
	}
yy495:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy496;
	default:	goto yy390;
	}
yy496:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy497;
	default:	goto yy390;
	}
yy497:
	++YYCURSOR;
#line 220 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_EVEN; }
#line 3080 "src/parser.cpp"
yy499:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy500;
	default:	goto yy390;
	}
yy500:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy501;
	default:	goto yy390;
	}
yy501:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy502;
	default:	goto yy390;
	}
yy502:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy503;
	default:	goto yy390;
	}
yy503:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy504;
	default:	goto yy390;
	}
yy504:
	++YYCURSOR;
#line 208 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_EXTERNAL; }
#line 3115 "src/parser.cpp"
yy506:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy507;
	default:	goto yy390;
	}
yy507:
	++YYCURSOR;
#line 221 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_ODD; }
#line 3126 "src/parser.cpp"
yy509:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy522;
	default:	goto yy390;
	}
yy510:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy514;
	default:	goto yy390;
	}
yy511:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy512;
	default:	goto yy390;
	}
yy512:
	++YYCURSOR;
#line 223 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_PMOD; }
#line 3149 "src/parser.cpp"
yy514:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'i':	goto yy516;
	default:	goto yy515;
	}
yy515:
#line 219 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MAX; }
#line 3160 "src/parser.cpp"
yy516:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy517;
	default:	goto yy390;
	}
yy517:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy518;
	default:	goto yy390;
	}
yy518:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':
	case 'z':	goto yy519;
	default:	goto yy390;
	}
yy519:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy520;
	default:	goto yy390;
	}
yy520:
	++YYCURSOR;
#line 202 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MAXIMIZE; }
#line 3190 "src/parser.cpp"
yy522:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'i':	goto yy524;
	default:	goto yy523;
	}
yy523:
#line 218 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MIN; }
#line 3201 "src/parser.cpp"
yy524:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy525;
	default:	goto yy390;
	}
yy525:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy526;
	default:	goto yy390;
	}
yy526:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':
	case 'z':	goto yy527;
	default:	goto yy390;
	}
yy527:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy528;
	default:	goto yy390;
	}
yy528:
	++YYCURSOR;
#line 201 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MINIMIZE; }
#line 3231 "src/parser.cpp"
yy530:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy534;
	default:	goto yy390;
	}
yy531:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'v':	goto yy532;
	default:	goto yy390;
	}
yy532:
	++YYCURSOR;
#line 224 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_PDIV; }
#line 3248 "src/parser.cpp"
yy534:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy535;
	default:	goto yy390;
	}
yy535:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy536;
	default:	goto yy390;
	}
yy536:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy537;
	default:	goto yy390;
	}
yy537:
	++YYCURSOR;
#line 207 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_DOMAIN; }
#line 3271 "src/parser.cpp"
yy539:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy540;
	default:	goto yy390;
	}
yy540:
	++YYCURSOR;
#line 225 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_PPOW; }
#line 3282 "src/parser.cpp"
yy542:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy546;
	default:	goto yy390;
	}
yy543:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy544;
	default:	goto yy390;
	}
yy544:
	++YYCURSOR;
#line 226 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_PABS; }
#line 3299 "src/parser.cpp"
yy546:
	++YYCURSOR;
#line 222 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_AVG; }
#line 3304 "src/parser.cpp"
yy548:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy549:
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy548;
	default:	goto yy292;
	}
yy550:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy551;
	default:	goto yy399;
	}
yy551:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy398;
	default:	goto yy552;
	}
yy552:
#line 188 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_PABS; }
#line 3393 "src/parser.cpp"
yy553:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy554;
	default:	goto yy399;
	}
yy554:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy398;
	default:	goto yy555;
	}
yy555:
#line 187 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_PPOW; }
#line 3471 "src/parser.cpp"
yy556:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'v':	goto yy557;
	default:	goto yy399;
	}
yy557:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy398;
	default:	goto yy558;
	}
yy558:
#line 186 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_PDIV; }
#line 3549 "src/parser.cpp"
yy559:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy571;
	default:	goto yy399;
	}
yy560:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy564;
	default:	goto yy399;
	}
yy561:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy562;
	default:	goto yy399;
	}
yy562:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy398;
	default:	goto yy563;
	}
yy563:
#line 185 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_PMOD; }
#line 3639 "src/parser.cpp"
yy564:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy565;
	default:	goto yy399;
	}
yy565:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy566;
	default:	goto yy399;
	}
yy566:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy567;
	default:	goto yy399;
	}
yy567:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':
	case 'z':	goto yy568;
	default:	goto yy399;
	}
yy568:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy569;
	default:	goto yy399;
	}
yy569:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy398;
	default:	goto yy570;
	}
yy570:
#line 189 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MINIMIZE; }
#line 3742 "src/parser.cpp"
yy571:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy572;
	default:	goto yy399;
	}
yy572:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy573;
	default:	goto yy399;
	}
yy573:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy574;
	default:	goto yy399;
	}
yy574:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':
	case 'z':	goto yy575;
	default:	goto yy399;
	}
yy575:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy576;
	default:	goto yy399;
	}
yy576:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy398;
	default:	goto yy577;
	}
yy577:
#line 190 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_MAXIMIZE; }
#line 3845 "src/parser.cpp"
yy578:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy580;
	case 'n':	goto yy579;
	default:	goto yy399;
	}
yy579:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy586;
	default:	goto yy399;
	}
yy580:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy581;
	default:	goto yy399;
	}
yy581:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy582;
	default:	goto yy399;
	}
yy582:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy583;
	default:	goto yy399;
	}
yy583:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy584;
	default:	goto yy399;
	}
yy584:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy398;
	default:	goto yy585;
	}
yy585:
#line 191 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_COMPUTE; }
#line 3954 "src/parser.cpp"
yy586:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy587;
	default:	goto yy399;
	}
yy587:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy398;
	default:	goto yy588;
	}
yy588:
#line 184 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_CONST; }
#line 4032 "src/parser.cpp"
yy589:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy590;
	default:	goto yy399;
	}
yy590:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy591;
	default:	goto yy399;
	}
yy591:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy398;
	default:	goto yy592;
	}
yy592:
#line 183 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_HIDE; }
#line 4116 "src/parser.cpp"
yy593:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy594;
	default:	goto yy399;
	}
yy594:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy595;
	default:	goto yy399;
	}
yy595:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy398;
	default:	goto yy596;
	}
yy596:
#line 182 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ return PARSER_SHOW; }
#line 4200 "src/parser.cpp"
}
#line 263 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"

lua:
	luaEnd = state().cursor_;
	
#line 4207 "src/parser.cpp"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 8) YYFILL(8);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy601;
	case '#':	goto yy599;
	default:	goto yy603;
	}
yy599:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'e':	goto yy604;
	default:	goto yy600;
	}
yy600:
#line 269 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ goto lua; }
#line 4226 "src/parser.cpp"
yy601:
	++YYCURSOR;
#line 268 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ if(eof()) { syntaxError(); return 0; } step(); goto lua; }
#line 4231 "src/parser.cpp"
yy603:
	yych = *++YYCURSOR;
	goto yy600;
yy604:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy606;
	default:	goto yy605;
	}
yy605:
	YYCURSOR = YYMARKER;
	goto yy600;
yy606:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy607;
	default:	goto yy605;
	}
yy607:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy608;
	default:	goto yy605;
	}
yy608:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy609;
	default:	goto yy605;
	}
yy609:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy610;
	default:	goto yy605;
	}
yy610:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy611;
	default:	goto yy605;
	}
yy611:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy611;
	case '.':	goto yy613;
	default:	goto yy605;
	}
yy613:
	++YYCURSOR;
#line 267 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ grounder()->luaExec(luaBegin_, string(10, state().cursor_ - luaEnd)); goto start; }
#line 4289 "src/parser.cpp"
}
#line 270 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"

blockcomment:
	
#line 4295 "src/parser.cpp"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy621;
	case '%':	goto yy619;
	case '*':	goto yy617;
	default:	goto yy623;
	}
yy617:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '%':	goto yy626;
	default:	goto yy618;
	}
yy618:
#line 277 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ goto blockcomment; }
#line 4315 "src/parser.cpp"
yy619:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy624;
	default:	goto yy620;
	}
yy620:
#line 275 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ goto comment; }
#line 4325 "src/parser.cpp"
yy621:
	++YYCURSOR;
#line 276 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ if(eof()) { syntaxError(); return 0; } step(); goto blockcomment; }
#line 4330 "src/parser.cpp"
yy623:
	yych = *++YYCURSOR;
	goto yy618;
yy624:
	++YYCURSOR;
#line 274 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ bc++; goto blockcomment; }
#line 4338 "src/parser.cpp"
yy626:
	++YYCURSOR;
#line 273 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ if(--bc == 0) goto start; goto blockcomment; }
#line 4343 "src/parser.cpp"
}
#line 278 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"

comment:
	
#line 4349 "src/parser.cpp"
{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy630;
	default:	goto yy632;
	}
yy630:
	++YYCURSOR;
#line 281 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ if(eof()) { if(bc > 0) syntaxError(); return 0; } step(); if(bc > 0) goto blockcomment; goto start; }
#line 4362 "src/parser.cpp"
yy632:
	++YYCURSOR;
#line 282 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"
	{ goto comment; }
#line 4367 "src/parser.cpp"
}
#line 283 "/home/kaminski/svn/potassco/tags/gringo-3.0.4/libgringo/src/parser.r2c"

}

void Parser::parseError()
{
	error_ = true;
}

std::string Parser::errorToken()
{
	if(eof()) return "<EOF>";
	else return string();
}

void Parser::syntaxError()
{
	errors_.push_back(ErrorTok(token_.loc(), errorToken()));
	error_ = true;
}

void Parser::include(uint32_t filename)
{
	include_ = filename;
}

void Parser::include()
{
	if(include_ != std::numeric_limits<uint32_t>::max())
	{
		const std::string &filename = grounder()->string(include_);
		include_ = std::numeric_limits<uint32_t>::max();
		streams_.addFile(filename);
	}
}

void Parser::parse(std::istream &in)
{
	token_.file = grounder()->index(streams_.currentFilename());
	reset(&in);
	int token;
	do
	{
		token = !compat_ ? lex() : lex_compat();
		parser(parser_, token, token_, this);
		add();
		include();
	}
	while(token != 0);
}

void Parser::parse()
{
	level_ = 1;
	do
	{
		parse(streams_.currentStream());
		if(error_)
		{
			ParseException ex;
			foreach(ErrorTok &tok, errors_)
				ex.add(StrLoc(g_, tok.first), tok.second);
			throw ex;
		}
	}
	while(streams_.next());
	incremental(IPART_BASE);
	foreach(DomainMap::const_reference val, grounder()->domains())
	{
		const std::string &name = grounder()->string(val.first.first);
		if(name.size() > 0 && name[0] == '-')
		{
			uint32_t pos = grounder()->index(std::string(name.begin() + 1, name.end()));
			Loc loc(grounder()->index("#internal"), 1, 1);
			TermPtrVec t1, t2;
			for(uint32_t i = 0; i < val.first.second; i++)
			{
				std::ostringstream oss;
				oss << "#I" << i;
				uint32_t index = grounder()->index(oss.str());
				t1.push_back(new VarTerm(loc, index));
				t2.push_back(new VarTerm(loc, index));
			}
			LitPtrVec body;
			body.push_back(new PredLit(loc, grounder()->domain(pos, val.first.second), t1));
			body.push_back(new PredLit(loc, grounder()->domain(val.first.first, val.first.second), t2));
			grounder()->add(new Rule(loc, 0, body));
		}
	}
}

void Parser::incremental(iPart part, uint32_t index)
{
	iPart_ = part;
	iId_   = index;
	if(part != IPART_BASE) { iVar_ = g_->index("#I"); }
}

Term *Parser::term(Val::Type t, const Loc &loc, uint32_t index)
{
	if(t == Val::ID)
	{
		if(iPart_ != IPART_BASE && index == iId_)
		{
			if(!iAdded_) { iLoc_ = loc; }
			iAdded_ = true;
			return new VarTerm(loc, iVar_);
		}
		else
		{
			ConstMap::const_iterator res = constMap_.find(index);
			if(res != constMap_.end()) { return res->second->clone(); }
			else                       { return new ConstTerm(loc, Val::create(Val::ID, index)); }
		}
	}
	else
	{
		assert(t == Val::STRING);
		return new ConstTerm(loc, Val::create(Val::STRING, index));
	}
}

namespace
{
	class IncVarFinder : public PrgVisitor
	{
	public:
		IncVarFinder(uint32_t var) : var_(var), found_(false) { }
		bool find(Statement *s) { s->visit(this); return found_; }

	private:
		void visit(VarTerm *var, bool bind)      { (void)bind; found_ = var_ == var->nameId(); }
		void visit(Term* term, bool bind)        { if(!found_) term->visit(this, bind); }
		void visit(Lit *lit, bool domain)        { (void)domain; if(!found_) lit->visit(this); }
		void visit(Groundable *grd, bool choice) { (void)choice; if(!found_) grd->visit(this); }

	private:
		uint32_t var_;
		bool     found_;
	};
}

void Parser::constTerm(uint32_t index, Term *term)
{
	constMap_.insert(index, term);
}

namespace
{

	class DomAdder : public PrgVisitor
	{
	private:
		typedef std::set<uint32_t> Seen;

	public:
		DomAdder(Parser *parser) : parser_(parser), statement_(0) { }
		void add(Statement *statement) { statement_ = statement; statement_->visit(this); }
	private:
		void visit(VarTerm *var, bool bind);
		void visit(Term *term, bool bind)        { term->visit(this, bind); }
		void visit(Lit *lit, bool domain)        { (void)domain; lit->visit(this); }
		void visit(Groundable *grd, bool choice) { (void)choice; grd->visit(this); }

	private:
		Parser    *parser_;
		Statement *statement_;
		Seen       seen_;
	};

	void DomAdder::visit(VarTerm *var, bool bind)
	{
		(void)bind;
		foreach(const Parser::DomStmMap::value_type &dom, parser_->domainStm(var->nameId()))
		{
			std::pair<Seen::iterator, bool> res = seen_.insert(dom.second->idx);
			if(res.second)
			{
				TermPtrVec terms;
				foreach(const VarSig &sig, dom.second->vars)
					terms.push_back(new VarTerm(sig.first, sig.second));
				statement_->append(new PredLit(dom.second->loc, parser_->grounder()->domain(dom.second->id, terms.size()), terms));
			}
		}
	}
}

void Parser::domainStm(const Loc &loc, uint32_t id, const VarSigVec &vars)
{
	domStmList_.push_back(DomStm(loc, domStmList_.size(), id, vars));
	foreach(const VarSig &var, vars)
		domStmMap_.insert(DomStmMap::value_type(var.second, &domStmList_.back()));
}

Parser::DomStmRng Parser::domainStm(uint32_t var)
{
	return DomStmRng(domStmMap_.lower_bound(var), domStmMap_.upper_bound(var));
}

void Parser::add(Statement *s)
{
	if(config_.incBase && iPart_ != IPART_BASE) { delete s; }
	else                                        { last_.push_back(s); }
}

void Parser::add()
{
	while(!last_.empty())
	{
		StatementRng rng(grounder()->add(last_.pop_back().release()));
		foreach(Statement &statement, rng)
		{
			DomAdder domAdder(this);
			domAdder.add(&statement);
		}
		if(iPart_ == IPART_CUMULATIVE && iAdded_)
		{
			foreach(Statement &statement, rng)
			{
				IncVarFinder finder(iVar_);
				if(finder.find(&statement))
				{
					statement.append(new IncLit(iLoc_, config_, true, iVar_));
				}
			}
		}
		else if(iPart_ == IPART_VOLATILE)
		{
			foreach(Statement &statement, rng)
			{
				statement.append(new IncLit(iLoc_, config_, false, iVar_));
			}
		}
		iAdded_ = false;
	}
}

PredLit *Parser::predLit(const Loc &loc, uint32_t id, TermPtrVec &terms, bool sign)
{
	if(sign) { id = grounder()->index(std::string("-") + grounder()->string(id)); }
	return new PredLit(loc, grounder()->domain(id, terms.size()), terms);
}

Parser::~Parser()
{
	parserFree(parser_, free);
}
